<a href="https://colab.research.google.com/github/ajasnizam/Assesment_2_NumPy_Pandas_Ajas.N/blob/main/NumPy_Pandas_Assessment_Ajas_N.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SECTION A (EASY)

In [13]:
#Q1

import numpy as np
temp = np.array([10, 20, 30, 40, 50])
print(temp)
print("Shape of the array is ",temp.shape)
print("Type of the array is ",type(temp))

[10 20 30 40 50]
Shape of the array is  (5,)
Type of the array is  <class 'numpy.ndarray'>


In [33]:
#Q2

import numpy as np
arr = np.array([5, 10, 15, 20, 25])
#adding 5 to all element
print(arr +5)
#multiplying 2 to all element
print(arr *2)

[10 15 20 25 30]
[10 20 30 40 50]


In [37]:
#Q3

arr = np.array([12, 15, 18, 20, 25, 30])
print('Mean : ',np.mean(arr))
print('Median : ',np.median(arr))
print('Minimum value: ',np.min(arr))
print('Maximum value: ',np.max(arr))
print('Standard Deviation : ',np.std(arr))

Mean :  20.0
Median :  19.0
Minimum value:  12
Maximum value:  30
Standard Deviation :  6.027713773341708


In [47]:
#Q4

arr = np.array([10, 25, 30, 45, 50, 65, 70])
result = arr[arr > 40]
print(result)

[45 50 65 70]


In [52]:
#Q5

import pandas as pd

data = {'Name': ['Anu', 'Rahul', 'Meera', 'Arun'],'Age': [21, 22, 20, 23],'Score': [85, 72, 91, 68]}
df

,Name,Age,Score
0,Anu,21,85
1,Rahul,22,72
2,Meera,20,91
3,Arun,23,68


In [64]:
#Q6

print("Displaying only the Name and Score columns")
print(df[['Name', 'Score']])
print("\n")
print("Displaying the complete record of Meera")
print(df[df['Name'] == 'Meera'])


Displaying only the Name and Score columns
    Name  Score
0    Anu     85
1  Rahul     72
2  Meera     91
3   Arun     68


Displaying the complete record of Meera
    Name  Age  Score
2  Meera   20     91


In [65]:
# Q7

filtered = df[df['Score'] > 75]

print(filtered)

    Name  Age  Score
0    Anu   21     85
2  Meera   20     91


In [92]:
#Q8

# 1. Number of rows and columns
print("Number of rows and columns:", df.shape)

# 2. Column names
print("Column names:", df.columns)

# 3. Data types
print("\nData types:\n", df.dtypes)

# 4. Basic statistical summary
print("\nBasic statistical summary:\n", df.describe())

Number of rows and columns: (4, 3)
Column names: Index(['Name', 'Age', 'Score'], dtype='object')

Data types:
 Name     object
Age       int64
Score     int64
dtype: object

Basic statistical summary:
              Age      Score
count   4.000000   4.000000
mean   21.500000  79.000000
std     1.290994  10.801234
min    20.000000  68.000000
25%    20.750000  71.000000
50%    21.500000  78.500000
75%    22.250000  86.500000
max    23.000000  91.000000


In [103]:
#Q9

sorted = df.sort_values(by='Score', ascending=False)
print(sorted)

    Name  Age  Score
2  Meera   20     91
0    Anu   21     85
1  Rahul   22     72
3   Arun   23     68


In [108]:
#Q10

df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D'],
    'Age': [21, np.nan, 23, 22],
    'Score': [80, 75, np.nan, 90]
})

# 1. Identify the missing values
print("Missing values:")
print(df.isnull())

# 2. Replace the missing Age with the mean age
df['Age'] = df['Age'].fillna(df['Age'].mean())

# 3. Replace the missing Score with the mean score
df['Score'] = df['Score'].fillna(df['Score'].mean())

Missing values:
    Name    Age  Score
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

Updated DataFrame:
  Name   Age      Score
0    A  21.0  80.000000
1    B  22.0  75.000000
2    C  23.0  81.666667
3    D  22.0  90.000000


SECTION B – MEDIUM


In [109]:
import pandas as pd


In [119]:
filepath = 'student_performance.csv'
df=pd.read_csv(filepath)
#Display the first 5 records
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9
...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4


In [130]:
#Q11

#1 Display the first 5 records
print("First 5 records:\n", df.head(5))
print("\n")
#2 Display the last 5 records
print("\nLast 5 records:\n", df.tail(5))
print("\n")
#3 Find the number of rows and columns
print("\nNumber of rows and columns:", df.shape)
print("\n")
#4 Display the column names
print("\nColumn names: \n)", df.columns)
print("\n")
#5 Display the data types
print("\nData types:\n", df.dtypes)
print("\n")
#6 Generate a statistical summary of the numerical columns
print("\nStatistical summary:\n", df.describe())

First 5 records:
   Student_ID            Name  Gender        Department   Age  Attendance  \
0    STU1001     Rahul Varma    Male  Computer Science  25.0        74.7   
1    STU1002    Kiran Pillai    Male  Computer Science  24.0        75.5   
2    STU1003  Fathima Joseph  Female       Electronics  21.0        60.5   
3    STU1004    Rahul Sharma  Female      Data Science  25.0        80.4   
4    STU1005       Asha Nair  Female      Data Science  22.0        71.4   

   Python_Score  SQL_Score  Pandas_Score  NumPy_Score  Final_Score  
0          89.4       86.3          81.9         76.7         82.7  
1          70.3       63.1          65.1         62.3         60.3  
2          79.9       80.4          65.3         68.0         67.1  
3          65.8       50.7          52.6         48.8         57.2  
4          90.1       82.9          72.4         87.7         81.9  



Last 5 records:
    Student_ID            Name  Gender        Department   Age  Attendance  \
75    STU1076 

In [131]:
#Q12

#1 Find students whose Final_Score is greater than 75
print("Students with Final_Score > 75:\n", df[df['Final_Score'] > 75])

#2 Find students whose Attendance is below 75%
print("\nStudents with Attendance < 75%:\n", df[df['Attendance'] < 75])

#3 Find students from the Data Science department with Final_Score greater than 80
print("\nData Science students with Final_Score > 80:\n",
      df[(df['Department'] == 'Data Science') & (df['Final_Score'] > 80)])

#4 Sort all students by Final_Score from highest to lowest
print("\nStudents sorted by Final_Score (highest to lowest):\n",
      df.sort_values(by='Final_Score', ascending=False))

Students with Final_Score > 75:
    Student_ID            Name  Gender        Department   Age  Attendance  \
0     STU1001     Rahul Varma    Male  Computer Science  25.0        74.7   
4     STU1005       Asha Nair  Female      Data Science  22.0        71.4   
6     STU1007     Akhil Varma    Male       Electronics  22.0        73.2   
7     STU1008     Akhil Varma    Male  Computer Science  20.0        81.1   
8     STU1009      Diya Menon    Male      Data Science  25.0        64.4   
10    STU1011        Diya Das  Female      Data Science  20.0       100.0   
11    STU1012      Arun Reddy    Male       Electronics  20.0        69.1   
16    STU1017    Rahul Thomas  Female      Data Science  25.0        78.3   
17    STU1018      Priya Nair    Male      Data Science  19.0        85.4   
23    STU1024  Fathima Joseph  Female          Commerce  23.0        78.2   
24    STU1025     Kiran Varma  Female       Electronics  21.0        80.7   
27    STU1028     Nikhil Nair  Female      

In [137]:
#Q13

df['Average_Technical_Score'] = df[['Python_Score', 'SQL_Score', 'Pandas_Score', 'NumPy_Score']].mean(axis=1)

# Display the first few rows to verify the new column
df[['Average_Technical_Score']].head()

# Define the conditions based on the rules
conditions = [(df['Average_Technical_Score'] >= 90),(df['Average_Technical_Score'] >= 75),(df['Average_Technical_Score'] >= 60),(df['Average_Technical_Score'] < 60)]

# Define the corresponding performance labels
choices = ['Excellent', 'Good', 'Average', 'Needs Improvement']

# Apply the conditions to create the new column (using 'Unknown' as default to match string data type)
df['Performance'] = np.select(conditions, choices, default='Unknown')

# Display the resulting DataFrame
df

,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
1,STU1002,Kiran Pillai,Male,Computer Science,24.0,75.5,70.3,63.1,65.1,62.3,60.3,65.200,Average
2,STU1003,Fathima Joseph,Female,Electronics,21.0,60.5,79.9,80.4,65.3,68.0,67.1,73.400,Average
3,STU1004,Rahul Sharma,Female,Data Science,25.0,80.4,65.8,50.7,52.6,48.8,57.2,54.475,Needs Improvement
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,STU1076,Priya Kumar,Female,Computer Science,24.0,99.3,46.9,57.6,29.5,57.1,47.2,47.775,Needs Improvement
76,STU1077,Amal Kumar,Male,Data Science,NaN,93.8,45.8,43.4,58.1,38.8,43.5,46.525,Needs Improvement
77,STU1078,Fathima Sharma,Male,Computer Science,19.0,86.4,70.4,75.7,98.2,76.7,75.2,80.250,Good
78,STU1079,Meera Thomas,Male,Electronics,23.0,99.4,64.6,66.5,61.8,52.5,63.4,61.350,Average


In [139]:
#Q14

#Grouping by Department and calculating statistics on Final_Score
dept_summary = df.groupby('Department')['Final_Score'].agg(Number_of_Students='count',Average_Final_Score='mean',Maximum_Final_Score='max',Minimum_Final_Score='min').reset_index()

#Sorting by Average Final Score in descending order
dept_summary_sorted = dept_summary.sort_values(by='Average_Final_Score', ascending=False)

#Displaying the resulting DataFrame
display(dept_summary_sorted)

,Department,Number_of_Students,Average_Final_Score,Maximum_Final_Score,Minimum_Final_Score
5,Electronics,13,72.846154,86.9,51.2
2,Computer Science,29,71.479310,96.0,40.6
4,Data Science,25,71.324000,97.0,43.5
1,Commerce,8,67.825000,83.7,54.6
6,data science,1,66.900000,66.9,66.9
0,Data Science,1,55.100000,55.1,55.1
3,Computer science,1,46.700000,46.7,46.7


In [145]:
#Q15
import numpy as np

#Convert the Final_Score column into a NumPy array.
score = df['Final_Score'].dropna().to_numpy()

#Calculate using NumPy:
mean_score = np.mean(score)
median_score = np.median(score)
std_dev = np.std(score)
pct_25 = np.percentile(score, 25)
pct_75 = np.percentile(score, 75)
#mean
print(f"Mean Final Score: {mean_score:0.2f}")
#median
print(f"Median Final Score: {median_score:0.2f}")
#standard deviation
print(f"Standard Deviation: {std_dev:0.2f}")
#25th percentile
print(f"25th Percentile: {pct_25:0.2f}")
#75th percentile
print(f"75th Percentile: {pct_75:0.2f}")

#Identify all students whose Final_Score is above the overall mean.
above_mean_students = df[df['Final_Score'] > mean_score]

print(f"\nNumber of students with Final_Score above the overall mean ({mean_score:.2f}): {len(above_mean_students)}")
display(above_mean_students)

Mean Final Score: 70.70
Median Final Score: 70.95
Standard Deviation: 13.96
25th Percentile: 60.45
75th Percentile: 82.28

Number of students with Final_Score above the overall mean (70.70): 42


,Student_ID,Name,Gender,Department,Age,Attendance,Python_Score,SQL_Score,Pandas_Score,NumPy_Score,Final_Score,Average_Technical_Score,Performance
0,STU1001,Rahul Varma,Male,Computer Science,25.0,74.7,89.4,86.3,81.9,76.7,82.7,83.575,Good
4,STU1005,Asha Nair,Female,Data Science,22.0,71.4,90.1,82.9,72.4,87.7,81.9,83.275,Good
6,STU1007,Akhil Varma,Male,Electronics,22.0,73.2,81.7,82.2,81.5,64.2,77.0,77.400,Good
7,STU1008,Akhil Varma,Male,Computer Science,20.0,81.1,72.1,80.4,72.9,73.5,79.2,74.725,Average
8,STU1009,Diya Menon,Male,Data Science,25.0,64.4,94.8,86.0,87.7,100.0,83.0,92.125,Excellent
9,STU1010,Gokul Pillai,Female,Computer Science,19.0,67.3,79.6,85.0,74.1,80.5,73.8,79.800,Good
10,STU1011,Diya Das,Female,Data Science,20.0,100.0,100.0,93.2,100.0,89.3,91.9,95.625,Excellent
11,STU1012,Arun Reddy,Male,Electronics,20.0,69.1,80.4,78.0,88.9,77.1,86.9,81.100,Good
16,STU1017,Rahul Thomas,Female,Data Science,25.0,78.3,80.8,99.4,77.2,100.0,91.1,89.350,Good
17,STU1018,Priya Nair,Male,Data Science,19.0,85.4,62.6,81.6,79.6,75.5,75.1,74.825,Average


SECTION C – HARD

In [158]:
#Q17(A)

#1 Load the CSV file
filepath = 'sales.csv'
df = pd.read_csv(filepath)

#2 Convert Order_Date to datetime type, handling mixed date formats
df['Order_Date'] = pd.to_datetime(df['Order_Date'], format='mixed', dayfirst=True)

#3 Check for missing values Handle missing values appropriately
print("Missing values per column:")
print(df.isnull().sum())

df = df.dropna()
print("\nDataFrame info after preprocessing:")
print(df.info())
print("\nFirst 5 rows:")
display(df.head())

Missing values per column:
Order_ID      0
Order_Date    0
Product       0
Category      0
Region        1
Sales         0
Quantity      1
Discount      0
Profit        1
dtype: int64

DataFrame info after preprocessing:
<class 'pandas.core.frame.DataFrame'>
Index: 177 entries, 0 to 179
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   Order_ID    177 non-null    object        
 1   Order_Date  177 non-null    datetime64[ns]
 2   Product     177 non-null    object        
 3   Category    177 non-null    object        
 4   Region      177 non-null    object        
 5   Sales       177 non-null    object        
 6   Quantity    177 non-null    float64       
 7   Discount    177 non-null    object        
 8   Profit      177 non-null    float64       
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 13.8+ KB
None

First 5 rows:


,Order_ID,Order_Date,Product,Category,Region,Sales,Quantity,Discount,Profit
0,ORD5001,2026-06-10,Office Chair,Furniture,East,142.1,1.0,0.02,12.78
1,ORD5002,2026-04-25,USB Hub,Accessories,North,51.52,2.0,0.08,4.57
2,ORD5003,2026-03-07,Monitor,Computers,West,648.0,4.0,0.1,86.32
3,ORD5004,2026-03-19,Office Chair,Furniture,North,290.0,2.0,0.0,47.77
4,ORD5005,2026-01-25,Tablet,Computers,North,304.0,1.0,0.05,23.43


In [160]:
#Q17(B)


#1 Calculate Total sales, Total profit, Average sales
total_sales = df['Sales'].sum()
total_profit = df['Profit'].sum()
avg_sales = df['Sales'].mean()

print(f"Total Sales: {total_sales:,.2f}")
print(f"Total Profit: {total_profit:,.2f}")
print(f"Average Sales: {avg_sales:,.2f}")

#2 Top 5 products based on sales
top_5_products = df.groupby('Product')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False).head(5)
print("\nTop 5 Products based on Sales:")
display(top_5_products)

#3 Region generating the highest sales
region_sales = df.groupby('Region')['Sales'].sum().reset_index().sort_values(by='Sales', ascending=False)
best_region = region_sales.iloc[0]
print(f"\nRegion generating the highest sales: {best_region['Region']} ({best_region['Sales']:,.2f})")

Total Sales: 93,712.94
Total Profit: 15,096.69
Average Sales: 529.45

Top 5 Products based on Sales:


,Product,Sales
4,Laptop,33995.0
7,Printer,13719.3
8,Tablet,10291.2
5,Monitor,9148.9
2,Headphones,5765.5



Region generating the highest sales: West (37,314.18)


In [166]:
#Q17(C)

# Sort by Total Sales in descending order
category_summary_sorted = category_summary.sort_values(by='Total_Sales', ascending=False)
display(category_summary_sorted)

,Category,Total_Sales,Total_Profit,Average_Discount
2,Computers,54587.10,8960.95,0.000653
4,Office Equipment,13719.30,2176.64,0.000584
1,Accessories,12630.78,2008.68,0.001384
3,Furniture,7329.46,1113.32,0.000748
5,Storage,5316.30,806.16,0.000754
0,Accessories,130.00,30.94,0.000000


# Q17(D) Business Insights & Observations

 Observations:
 1 Laptops and Computers drive our business Most of our sales and profits come from computers, specifically laptops. We should focus our inventory and marketing here
 2 The West is our best market by far The West region generates far more sales than places like the East. We should copy our West strategy in other regions to help them grow
 3 Accessories bring in easy profit Items like accessories don't need big discounts to sell, making them highly profitable for their size